CREATE TABLE ADMIN.BANCO_IMAGENS 
    ( 
     ID_BANCO_IMAGENS          NUMBER (*,0) , 
     ID_PROJETOS               NUMBER (*,0)  NOT NULL , 
     DESCRICAO_IMG_ORIGINAL    VARCHAR2 (100)  NOT NULL , 
     IMG_ORIGINAL              BLOB , 
     ALTURA_IMG_ORIGINAL       NUMBER (*,0)  NOT NULL , 
     LARGURA_IMG_ORIGINAL      NUMBER (*,0)  NOT NULL , 
     NUM_CANAIS_IMG_ORIGINAL   NUMBER (*,0)  NOT NULL , 
     TOTAL_PIXELS_IMG_ORIGINAL NUMBER (*,0)  NOT NULL , 
     TIPO_IMG_ORIGINAL         VARCHAR2 (45)  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        INITRANS 10 
        TABLESPACE DATA 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
    LOB ( IMG_ORIGINAL ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
;


CREATE UNIQUE INDEX ADMIN.BANCO_IMAGENS_PRIMARY ON ADMIN.BANCO_IMAGENS 
    ( 
     ID_BANCO_IMAGENS ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

CREATE INDEX ADMIN.FK_BANCO_IMAG_PROJETOS1_IDX ON ADMIN.BANCO_IMAGENS 
    ( 
     ID_PROJETOS ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE ADMIN.BANCO_IMAGENS 
    ADD CONSTRAINT BANCO_IMAGENS_PRIMARY PRIMARY KEY ( ID_BANCO_IMAGENS ) 
    USING INDEX ADMIN.BANCO_IMAGENS_PRIMARY ;

CREATE TABLE ADMIN.CLASSIFICACOES 
    ( 
     ID_CLASSIFICACAO        NUMBER (*,0) , 
     ID_PROJETOS             NUMBER (*,0)  NOT NULL , 
     RESULTADO               NUMBER (*,0)  NOT NULL , 
     ID_BANCO_IMAGENS        NUMBER (*,0)  NOT NULL , 
     PORCENTAGEM_TREINO      NUMBER (*,0) , 
     PORCENTAGEM_TESTE       NUMBER (*,0) , 
     TIPO_CLASSIFICACAO      VARCHAR2 (30)  NOT NULL , 
     RELATORIO_CLASSIFICACAO CLOB , 
     MATRIZ_CONFUSAO         BLOB , 
     CURVA_ROC               BLOB , 
     TUPLAS_BINARIAS         NUMBER , 
     TUPLAS_BINARIAS_LIMPAS  NUMBER , 
     PERC_TUPLAS_DUPL_ELIMIN FLOAT (126) 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        INITRANS 10 
        TABLESPACE DATA 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
    LOB ( RELATORIO_CLASSIFICACAO ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
    LOB ( MATRIZ_CONFUSAO ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
    LOB ( CURVA_ROC ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
;


CREATE UNIQUE INDEX ADMIN.CLASSIFICACOES_PRIMARY ON ADMIN.CLASSIFICACOES 
    ( 
     ID_CLASSIFICACAO ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

CREATE INDEX ADMIN.FK_CLASSIFICACAO_PROJETOS1_IDX ON ADMIN.CLASSIFICACOES 
    ( 
     ID_PROJETOS ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE ADMIN.CLASSIFICACOES 
    ADD CONSTRAINT CLASSIFICACOES_PRIMARY PRIMARY KEY ( ID_CLASSIFICACAO ) 
    USING INDEX ADMIN.CLASSIFICACOES_PRIMARY ;

CREATE TABLE ADMIN.DADOS_CLIMATICOS 
    ( 
     ID_DADOS_CLIMATICOS        NUMBER (*,0) , 
     ID_PROJETOS                NUMBER (*,0)  NOT NULL , 
     LOCAL_ESTACAO_CLIMATICA    VARCHAR2 (150)  NOT NULL , 
     PERIODO_MEDICAO            VARCHAR2 (40)  NOT NULL , 
     DATA_MEDICAO               DATE  NOT NULL , 
     PRECIPITACAO               FLOAT (126)  NOT NULL , 
     TEMPERATURA_MAX            FLOAT (126)  NOT NULL , 
     TEMPERATURA_MIN            FLOAT (126)  NOT NULL , 
     UMIDADE_RELATIVA           FLOAT (126)  NOT NULL , 
     PONTO_ORVALHO              FLOAT (126)  NOT NULL , 
     TEMPERATURA_MED_COMPENSADA FLOAT (126)  NOT NULL , 
     REGIAO_ESTACAO_CLIMATICA   VARCHAR2 (150)  NOT NULL , 
     STATUS                     VARCHAR2 (20) 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        INITRANS 10 
        TABLESPACE DATA 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
;


CREATE UNIQUE INDEX ADMIN.DADOS_CLIMATICOS_PRIMARY ON ADMIN.DADOS_CLIMATICOS 
    ( 
     ID_DADOS_CLIMATICOS ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

CREATE INDEX ADMIN.FK_DADOS_CLIMAT_PROJETO1_IDX ON ADMIN.DADOS_CLIMATICOS 
    ( 
     ID_PROJETOS ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE ADMIN.DADOS_CLIMATICOS 
    ADD CONSTRAINT DADOS_CLIMATICOS_PRIMARY PRIMARY KEY ( ID_DADOS_CLIMATICOS ) 
    USING INDEX ADMIN.DADOS_CLIMATICOS_PRIMARY ;

CREATE TABLE ADMIN.DADOS_PLANTA_SOJA 
    ( 
     ID_DADOS_PLANTA_SOJA     NUMBER (*,0) , 
     ID_PROJETOS              NUMBER (*,0) , 
     VARIEDADE_CULTURA        VARCHAR2 (200) , 
     DISTANCIA_LINHA_CULTURA  FLOAT (126) , 
     ALTURA_PLANTA_CULTURA    FLOAT (126) , 
     DISTANCIA_PLANTA_CULTURA FLOAT (126) , 
     PLANTAS_METRO_LINEAR     NUMBER , 
     STATUS                   VARCHAR2 (50) 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        INITRANS 10 
        TABLESPACE DATA 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
;


CREATE UNIQUE INDEX ADMIN.DADOS_PLANTA_SOJA_PRIMARY ON ADMIN.DADOS_PLANTA_SOJA 
    ( 
     ID_DADOS_PLANTA_SOJA ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

CREATE INDEX ADMIN.FK_DAD_PLANT_SOJA_PROJETO1_IDX ON ADMIN.DADOS_PLANTA_SOJA 
    ( 
     ID_PROJETOS ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE ADMIN.DADOS_PLANTA_SOJA 
    ADD CONSTRAINT DADOS_PLANTA_SOJA_PRIMARY PRIMARY KEY ( ID_DADOS_PLANTA_SOJA ) 
    USING INDEX ADMIN.DADOS_PLANTA_SOJA_PRIMARY ;

CREATE TABLE ADMIN.FAVORABILIDADES_FAS 
    ( 
     ID_FAVORABILIDADE        NUMBER (*,0) , 
     RESULTADO_FAVORABILIDADE VARCHAR2 (500)  NOT NULL , 
     VETOR_FAVORABILIDADE     VARCHAR2 (500)  NOT NULL , 
     ID_BANCO_IMAGENS         NUMBER (*,0)  NOT NULL , 
     JANELA_TEMPO_INICIAL     DATE  NOT NULL , 
     JANELA_TEMPO_FINAL       DATE  NOT NULL , 
     ABORDAGEM_FUSAO_DADOS    VARCHAR2 (100)  NOT NULL , 
     V1                       NUMBER , 
     V2                       NUMBER , 
     V3                       NUMBER , 
     V4                       NUMBER , 
     V5                       NUMBER , 
     V6                       NUMBER , 
     V7                       NUMBER 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        INITRANS 10 
        TABLESPACE DATA 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
;


CREATE UNIQUE INDEX ADMIN.FAVORABILIDADE_FAS_PK ON ADMIN.FAVORABILIDADES_FAS 
    ( 
     ID_FAVORABILIDADE ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE ADMIN.FAVORABILIDADES_FAS 
    ADD CONSTRAINT FAVORABILIDADE_FAS_PK PRIMARY KEY ( ID_FAVORABILIDADE ) 
    USING INDEX ADMIN.FAVORABILIDADE_FAS_PK ;

CREATE TABLE ADMIN.FUNGICIDAS 
    ( 
     TRATAMENTO           VARCHAR2 (100)  NOT NULL , 
     DOSAGEM_1            VARCHAR2 (50) , 
     DOSAGEM_2            VARCHAR2 (50) , 
     SEVERIDADE           FLOAT (126) , 
     PORCENTAGEM_CONTROLE FLOAT (126) , 
     PRODUTIVIDADE        NUMBER , 
     ID_FUNGICIDA         NUMBER GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 MAXVALUE 9999999999 NOCACHE ) 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        INITRANS 10 
        TABLESPACE DATA 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
;


CREATE UNIQUE INDEX ADMIN.FUNGICIDAS_PK ON ADMIN.FUNGICIDAS 
    ( 
     ID_FUNGICIDA ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE ADMIN.FUNGICIDAS 
    ADD CONSTRAINT FUNGICIDAS_PK PRIMARY KEY ( ID_FUNGICIDA ) 
    USING INDEX ADMIN.FUNGICIDAS_PK ;

CREATE TABLE ADMIN.IMAGEM_CLIMA_FAVORAB 
    ( 
     ID_IMAGEM_CLIMA_FAVORAB NUMBER (*,0) , 
     ID_BANCO_IMAGENS        NUMBER (*,0)  NOT NULL , 
     ID_TAB_VERD_FAVORAB     NUMBER (*,0)  NOT NULL , 
     ID_DADOS_CLIMATICOS     NUMBER (*,0)  NOT NULL , 
     DESC_FAVORAB            VARCHAR2 (40) , 
     ID_DADOS_PLANTA_SOJA    NUMBER 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        INITRANS 10 
        TABLESPACE DATA 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
;


CREATE UNIQUE INDEX ADMIN.IMAGEM_CLIMA_FAVORAB_PK ON ADMIN.IMAGEM_CLIMA_FAVORAB 
    ( 
     ID_IMAGEM_CLIMA_FAVORAB ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE ADMIN.IMAGEM_CLIMA_FAVORAB 
    ADD CONSTRAINT IMAGEM_CLIMA_FAVORAB_PK PRIMARY KEY ( ID_IMAGEM_CLIMA_FAVORAB ) 
    USING INDEX ADMIN.IMAGEM_CLIMA_FAVORAB_PK ;

CREATE TABLE ADMIN.IMAGENS_SEGMENTADAS 
    ( 
     ID_IMG_SEGMENTADAS                NUMBER (*,0) , 
     IMG_SEGMENT_REFERENCIA            BLOB , 
     IMG_FILTRO_MEDIANA                BLOB , 
     IMG_CANAL_VERDE                   BLOB , 
     IMG_JANELA                        BLOB , 
     IMG_LIMIARIZADA                   BLOB , 
     CLASSE_COR                        VARCHAR2 (30) , 
     DESCRICAO_IMG_ORIGEM              VARCHAR2 (60) , 
     ID_BANCO_IMAGENS                  NUMBER , 
     IMG_ROTULO_ESCOLHIDO              BLOB , 
     MSE                               FLOAT (126) , 
     PSNR                              FLOAT (126) , 
     SSIM                              FLOAT (126) , 
     HISTOGRAMA                        BLOB , 
     BOXPLOT_SEMENTES                  BLOB , 
     BOXPLOT_SEMENTES_CALCULO          BLOB , 
     OUTLIERS_BOXPLOT_SEMENTES         NUMBER (*,0) , 
     OUTLIERS_BOXPLOT_SEMENTES_CALCULO NUMBER (*,0) 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        INITRANS 10 
        TABLESPACE DATA 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
    LOB ( BOXPLOT_SEMENTES ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
    LOB ( BOXPLOT_SEMENTES_CALCULO ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
    LOB ( IMG_SEGMENT_REFERENCIA ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
    LOB ( IMG_FILTRO_MEDIANA ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
    LOB ( IMG_CANAL_VERDE ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
    LOB ( IMG_JANELA ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
    LOB ( IMG_LIMIARIZADA ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
    LOB ( IMG_ROTULO_ESCOLHIDO ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
    LOB ( HISTOGRAMA ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
;


CREATE UNIQUE INDEX ADMIN.IMAGENS_SEGMENTADAS_PRIMARY ON ADMIN.IMAGENS_SEGMENTADAS 
    ( 
     ID_IMG_SEGMENTADAS ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE ADMIN.IMAGENS_SEGMENTADAS 
    ADD CONSTRAINT IMAGENS_SEGMENTADAS_PRIMARY PRIMARY KEY ( ID_IMG_SEGMENTADAS ) 
    USING INDEX ADMIN.IMAGENS_SEGMENTADAS_PRIMARY ;

CREATE TABLE ADMIN.PROJETOS 
    ( 
     ID_PROJETOS  NUMBER (*,0) , 
     NOME_PROJETO VARCHAR2 (200)  NOT NULL , 
     TIPO_PROJETO VARCHAR2 (100)  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        INITRANS 10 
        TABLESPACE DATA 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
;


CREATE UNIQUE INDEX ADMIN.PROJETOS_PRIMARY ON ADMIN.PROJETOS 
    ( 
     ID_PROJETOS ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE ADMIN.PROJETOS 
    ADD CONSTRAINT PROJETOS_PRIMARY PRIMARY KEY ( ID_PROJETOS ) 
    USING INDEX ADMIN.PROJETOS_PRIMARY ;

CREATE TABLE ADMIN.RECOMENDACOES 
    ( 
     RECOMENDACAO_FAVORAB_BAIXA CLOB , 
     RECOMENDACAO_FAVORAB_MEDIA CLOB , 
     RECOMENDACAO_FAVORAB_ALTA  CLOB , 
     ID_RECOMENDACAO            NUMBER GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 MAXVALUE 999999999 NOCACHE ) 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        INITRANS 10 
        TABLESPACE DATA 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
    LOB ( RECOMENDACAO_FAVORAB_BAIXA ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
    LOB ( RECOMENDACAO_FAVORAB_MEDIA ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
    LOB ( RECOMENDACAO_FAVORAB_ALTA ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
;


CREATE UNIQUE INDEX ADMIN.RECOMENDACOES_PK ON ADMIN.RECOMENDACOES 
    ( 
     ID_RECOMENDACAO ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE ADMIN.RECOMENDACOES 
    ADD CONSTRAINT RECOMENDACOES_PK PRIMARY KEY ( ID_RECOMENDACAO ) 
    USING INDEX ADMIN.RECOMENDACOES_PK ;

CREATE TABLE ADMIN.RECOMENDACOES_FUNGICIDAS 
    ( 
     ID_FUNGICIDA               NUMBER  NOT NULL , 
     ID_RECOMENDACOES_FUNGICIDA NUMBER GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 MAXVALUE 9999999999 NOCACHE )  NOT NULL , 
     ID_RECOMENDACOES           NUMBER  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        INITRANS 10 
        TABLESPACE DATA 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
;


CREATE UNIQUE INDEX ADMIN.PLANTA_FUNGICIDAS_PK ON ADMIN.RECOMENDACOES_FUNGICIDAS 
    ( 
     ID_RECOMENDACOES_FUNGICIDA ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

CREATE TABLE ADMIN.ROTULOS_SEGMENTADOS 
    ( 
     ID_ROTULOS_SEGMENTADOS NUMBER (*,0) , 
     ID_SEGMENTACAO         NUMBER (*,0) , 
     IMG_ROTULO_SEGMENTADO  BLOB , 
     CLASSE_COR             VARCHAR2 (30) 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        INITRANS 10 
        TABLESPACE DATA 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
    LOB ( IMG_ROTULO_SEGMENTADO ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
;


CREATE UNIQUE INDEX ADMIN.ROTULOS_SEGMENTADOS_PRIMARY ON ADMIN.ROTULOS_SEGMENTADOS 
    ( 
     ID_ROTULOS_SEGMENTADOS ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE ADMIN.ROTULOS_SEGMENTADOS 
    ADD CONSTRAINT ROTULOS_SEGMENTADOS_PRIMARY PRIMARY KEY ( ID_ROTULOS_SEGMENTADOS ) 
    USING INDEX ADMIN.ROTULOS_SEGMENTADOS_PRIMARY ;

CREATE TABLE ADMIN.SEGMENTACAO 
    ( 
     ID_SEGMENTACAO               NUMBER (*,0) , 
     ID_PROJETOS                  NUMBER (*,0)  NOT NULL , 
     ID_IMG_SEGMENTADAS           NUMBER (*,0)  NOT NULL , 
     ID_SEMENTES                  NUMBER (*,0)  NOT NULL , 
     DATA_HORA_PROJETO            VARCHAR2 (25)  NOT NULL , 
     COORDENADAS_SEMENTE_CENTRAL  VARCHAR2 (15)  NOT NULL , 
     COORDENADAS_CALC_JANELA      VARCHAR2 (100)  NOT NULL , 
     TOTAL_PIXELS_JANELA          NUMBER (*,0)  NOT NULL , 
     TOTAL_SEMENTES_CALCULADAS    NUMBER (*,0)  NOT NULL , 
     ERRO_ESTATISTICO_CALCULADO   FLOAT (126)  NOT NULL , 
     OPERACAO_PROJETO             VARCHAR2 (100)  NOT NULL , 
     DESVIO_PADRAO_PROJETO        FLOAT (126)  NOT NULL , 
     LIMIAR_1_SEGMENTACAO         NUMBER (*,0)  NOT NULL , 
     LIMIAR_2_SEGMENTACAO         NUMBER (*,0)  NOT NULL , 
     FAIXA_LIMIARES               VARCHAR2 (30)  NOT NULL , 
     VARIANCIA_SEGMENTACAO        FLOAT (126)  NOT NULL , 
     COORD_JANELA_FINAL_OBJ_INTER VARCHAR2 (40)  NOT NULL , 
     SEMENTES_CALCULADAS_JANELA   CLOB  NOT NULL , 
     RELATORIO_COLETA_AUT_SEMENTE CLOB  NOT NULL , 
     RELATORIO_DADOS_ESTATISTICOS CLOB  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        INITRANS 10 
        TABLESPACE DATA 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
    LOB ( SEMENTES_CALCULADAS_JANELA ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
    LOB ( RELATORIO_COLETA_AUT_SEMENTE ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
    LOB ( RELATORIO_DADOS_ESTATISTICOS ) STORE AS SECUREFILE 
        ( 
        TABLESPACE DATA 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW 
        NOCACHE LOGGING 
    ) 
;


CREATE INDEX ADMIN.FK_SEGMENT_IMG_SEGMENT1_IDX ON ADMIN.SEGMENTACAO 
    ( 
     ID_IMG_SEGMENTADAS ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

CREATE INDEX ADMIN.FK_SEGMENT_PROJETOS1_IDX ON ADMIN.SEGMENTACAO 
    ( 
     ID_PROJETOS ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

CREATE INDEX ADMIN.FK_SEGMENT_SEMENTES1_IDX ON ADMIN.SEGMENTACAO 
    ( 
     ID_SEMENTES ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

CREATE UNIQUE INDEX ADMIN.SEGMENTACAO_PRIMARY ON ADMIN.SEGMENTACAO 
    ( 
     ID_SEGMENTACAO ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE ADMIN.SEGMENTACAO 
    ADD CONSTRAINT SEGMENTACAO_PRIMARY PRIMARY KEY ( ID_SEGMENTACAO ) 
    USING INDEX ADMIN.SEGMENTACAO_PRIMARY ;

CREATE TABLE ADMIN.SEMENTES 
    ( 
     ID_SEMENTES           NUMBER (*,0) , 
     DESCRICAO_COR_SEMENTE VARCHAR2 (100)  NOT NULL , 
     COR_RGB_SEMENTE       VARCHAR2 (45)  NOT NULL , 
     DADOS_SEMENTES        LONG 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        INITRANS 10 
        TABLESPACE DATA 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
;


CREATE UNIQUE INDEX ADMIN.SEMENTES_PK ON ADMIN.SEMENTES 
    ( 
     ID_SEMENTES ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE ADMIN.SEMENTES 
    ADD CONSTRAINT SEMENTES_PK PRIMARY KEY ( ID_SEMENTES ) 
    USING INDEX ADMIN.SEMENTES_PK ;

CREATE TABLE ADMIN.TAB_VERD_FAVORABILIDADE 
    ( 
     ID_TAB_VERD_FAVORAB NUMBER (*,0)  NOT NULL , 
     V1                  NUMBER (*,0)  NOT NULL , 
     V2                  NUMBER (*,0)  NOT NULL , 
     V3                  NUMBER (*,0)  NOT NULL , 
     V4                  NUMBER (*,0)  NOT NULL , 
     V5                  NUMBER (*,0)  NOT NULL , 
     V6                  NUMBER (*,0)  NOT NULL , 
     V7                  NUMBER (*,0)  NOT NULL , 
     S                   NUMBER (*,0)  NOT NULL , 
     P_V1                FLOAT (126)  NOT NULL , 
     P_V2                FLOAT (126)  NOT NULL , 
     P_V3                FLOAT (126)  NOT NULL , 
     P_V4                FLOAT (126)  NOT NULL , 
     P_V5                FLOAT (126)  NOT NULL , 
     P_V6                FLOAT (126)  NOT NULL , 
     P_V7                FLOAT (126)  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        INITRANS 10 
        TABLESPACE DATA 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
;


CREATE UNIQUE INDEX ADMIN.TABELA_VERDADE_FAVORABILIDADE_PK ON ADMIN.TAB_VERD_FAVORABILIDADE 
    ( 
     ID_TAB_VERD_FAVORAB ASC 
    ) 
    TABLESPACE DATA 
    PCTFREE 10 
    INITRANS 20 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE ADMIN.FAVORABILIDADES_FAS 
    ADD CONSTRAINT FAVORAB_FAS_BANCO_IMAGENS_FK FOREIGN KEY 
    ( 
     ID_BANCO_IMAGENS
    ) 
    REFERENCES ADMIN.BANCO_IMAGENS 
    ( 
         ID_BANCO_IMAGENS
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.BANCO_IMAGENS 
    ADD CONSTRAINT FK_BANCO_IMAG_PROJ FOREIGN KEY 
    ( 
     ID_PROJETOS
    ) 
    REFERENCES ADMIN.PROJETOS 
    ( 
         ID_PROJETOS
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.CLASSIFICACOES 
    ADD CONSTRAINT FK_CLASSIF_BANCO_IMAGENS FOREIGN KEY 
    ( 
     ID_BANCO_IMAGENS
    ) 
    REFERENCES ADMIN.BANCO_IMAGENS 
    ( 
         ID_BANCO_IMAGENS
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.CLASSIFICACOES 
    ADD CONSTRAINT FK_CLASSIF_PROJ FOREIGN KEY 
    ( 
     ID_PROJETOS
    ) 
    REFERENCES ADMIN.PROJETOS 
    ( 
         ID_PROJETOS
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.DADOS_CLIMATICOS 
    ADD CONSTRAINT FK_DADOS_CLIMATICOS_PROJ FOREIGN KEY 
    ( 
     ID_PROJETOS
    ) 
    REFERENCES ADMIN.PROJETOS 
    ( 
         ID_PROJETOS
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.DADOS_PLANTA_SOJA 
    ADD CONSTRAINT FK_DADOS_PLANTA_PROJ FOREIGN KEY 
    ( 
     ID_PROJETOS
    ) 
    REFERENCES ADMIN.PROJETOS 
    ( 
         ID_PROJETOS
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.IMAGENS_SEGMENTADAS 
    ADD CONSTRAINT FK_IMGS_SEGMENT_BANCO_IMGS FOREIGN KEY 
    ( 
     ID_BANCO_IMAGENS
    ) 
    REFERENCES ADMIN.BANCO_IMAGENS 
    ( 
         ID_BANCO_IMAGENS
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.IMAGEM_CLIMA_FAVORAB 
    ADD CONSTRAINT FK_IMG_CLI_FAV_BANCO_IMGS FOREIGN KEY 
    ( 
     ID_BANCO_IMAGENS
    ) 
    REFERENCES ADMIN.BANCO_IMAGENS 
    ( 
         ID_BANCO_IMAGENS
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.IMAGEM_CLIMA_FAVORAB 
    ADD CONSTRAINT FK_IMG_CLI_FAV_DADOS_CLIMATICOS FOREIGN KEY 
    ( 
     ID_DADOS_CLIMATICOS
    ) 
    REFERENCES ADMIN.DADOS_CLIMATICOS 
    ( 
         ID_DADOS_CLIMATICOS
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.IMAGEM_CLIMA_FAVORAB 
    ADD CONSTRAINT FK_IMG_CLI_FAV_DADOS_PL_SOJA FOREIGN KEY 
    ( 
     ID_DADOS_PLANTA_SOJA
    ) 
    REFERENCES ADMIN.DADOS_PLANTA_SOJA 
    ( 
         ID_DADOS_PLANTA_SOJA
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.ROTULOS_SEGMENTADOS 
    ADD CONSTRAINT FK_ROT_SEGMENT_SEGMENTACAO FOREIGN KEY 
    ( 
     ID_SEGMENTACAO
    ) 
    REFERENCES ADMIN.SEGMENTACAO 
    ( 
         ID_SEGMENTACAO
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.SEGMENTACAO 
    ADD CONSTRAINT FK_SEGMENT_IMG_SEGMENT FOREIGN KEY 
    ( 
     ID_IMG_SEGMENTADAS
    ) 
    REFERENCES ADMIN.IMAGENS_SEGMENTADAS 
    ( 
         ID_IMG_SEGMENTADAS
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.SEGMENTACAO 
    ADD CONSTRAINT FK_SEGMENT_PROJ FOREIGN KEY 
    ( 
     ID_PROJETOS
    ) 
    REFERENCES ADMIN.PROJETOS 
    ( 
         ID_PROJETOS
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.SEGMENTACAO 
    ADD CONSTRAINT FK_SEGMENT_SEMENT FOREIGN KEY 
    ( 
     ID_SEMENTES
    ) 
    REFERENCES ADMIN.SEMENTES 
    ( 
         ID_SEMENTES
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.RECOMENDACOES_FUNGICIDAS 
    ADD CONSTRAINT RECOMEND_FUNG_FUNGICIDAS_FK FOREIGN KEY 
    ( 
     ID_FUNGICIDA
    ) 
    REFERENCES ADMIN.FUNGICIDAS 
    ( 
         ID_FUNGICIDA
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ADMIN.RECOMENDACOES_FUNGICIDAS 
    ADD CONSTRAINT RECOMEND_FUNG_RECOMENDACOES_FK FOREIGN KEY 
    ( 
     ID_RECOMENDACOES
    ) 
    REFERENCES ADMIN.RECOMENDACOES 
    ( 
         ID_RECOMENDACAO
    ) 
    NOT DEFERRABLE 
;



