/* -----------------------SCRIPT DE CARGA PARA O DATA WAREHOUSE-------------------------------

ELABORADO POR: RICARDO ALEXANDRE NEVES
DOUTORADO EM CIÊNCIA DA COMPUTAÇÃO - UFSCar - SÃO CARLOS

1- USO DE FUNÇÃO DE MÍNIMO PARA AS COLUNAS PARA RETIRADA DE REPETIÇÕES DE DADOS,
    O QUE CAUSA VALORES ERRADOS NA SOMATÓRIA DOS DADOS POR ANO/MÊS/TRIMESTRE/DIA:
        ID_DADOS_CLIMATICOS; ID_IMAGEM_CLIMA_FAVORAB;
        ID_DADOS_PLANTA_SOJA; SK_DIM_TEMPO.
        
    AS DEMAIS COLUNAS QUE NÃO USAM A FUNÇÃO DE MÍNIMO DEVEM VIR NA CLÁUSULA GROUP BY;
    
2- USO DE INNER JOIN PARA O CRUZAMENTO DAS TABELAS PARA CONSEGUIR OS DADOS NECESSÁRIOS 
    PARA RESPONDER OS ASSUNTOS 1,2 E 3 DOS REQUISITOS ELENCADOS.
    
*/--------------------------------------------------------------------------------------------

SELECT DISTINCT
    MIN(B.SK_DIM_TEMPO) AS SK_DIM_TEMPO,
    C.ID_CLASSIFICACAO,
    H.ID_BANCO_IMAGENS,
    H.ID_FAVORABILIDADE,
    MIN(L.ID_DADOS_PLANTA_SOJA) AS ID_DADOS_PLANTA_SOJA,
    MIN(F.ID_IMAGEM_CLIMA_FAVORAB) AS ID_IMAGEM_CLIMA_FAVORAB,
    MIN(F.ID_DADOS_CLIMATICOS) AS ID_DADOS_CLIMATICOS,
    H.ABORDAGEM_FUSAO_DADOS,
    H.JANELA_TEMPO_INICIAL,
    H.JANELA_TEMPO_FINAL,
    H.RESULTADO_FAVORABILIDADE,
    C.RESULTADO AS RESULTADO_CLASSIFICACAO_IMG,
    H.V1 AS FAVORAB_V1_PERIODO_MOLHAMENTO_FOLIAR,
    H.V2 AS FAVORAB_V2_PERIODO_MIN_MOLHAMENTO_FOLIAR,
    H.V3 AS FAVORAB_V3_FAIXA_TEMPERATURA,
    H.V4 AS FAVORAB_V4_TEMPERATURA_MAXIMA,
    H.V5 AS FAVORAB_V5_TEMPERATURA_MINIMA,
    H.V6 AS FAVORAB_V6_PONTO_ORVALHO,
    H.V7 AS FAVORAB_V7_DADOS_CULTIVAR_CLASSIF_IMAGEM
    
FROM
    VIEW_DIM_FAVORABILIDADES_FAS H

INNER JOIN TEMPO B
ON B.DATA = H.JANELA_TEMPO_INICIAL

INNER JOIN TEMPO B
ON B.DATA = H.JANELA_TEMPO_FINAL

INNER JOIN VIEW_DIM_CLASSIFICACOES C
ON C.ID_BANCO_IMAGENS = H.ID_BANCO_IMAGENS

INNER JOIN VIEW_DIM_IMAGEM_CLIMA_FAVORAB F
ON F.ID_BANCO_IMAGENS = H.ID_BANCO_IMAGENS

INNER JOIN VIEW_DIM_DADOS_PLANTA_SOJA L
ON L.ID_DADOS_PLANTA_SOJA = F.ID_DADOS_PLANTA_SOJA

WHERE H.abordagem_fusao_dados='Cadeias Ocultas de Markov' 

GROUP BY 
    C.ID_CLASSIFICACAO,
    H.ID_BANCO_IMAGENS,
    H.ID_FAVORABILIDADE, 
    H.ABORDAGEM_FUSAO_DADOS,
    H.JANELA_TEMPO_INICIAL,
    H.JANELA_TEMPO_FINAL, 
    H.RESULTADO_FAVORABILIDADE,
    C.RESULTADO,
    H.V1,
    H.V2,
    H.V3, 
    H.V4,
    H.V5,
    H.V6,
    H.V7;